// Generated by CoffeeScript 1.7.1
(function() {
  var Hapi, Lab;

  require('coffee-script/register');

  Lab = require("lab");

  Hapi = require('hapi');

  Lab.experiment("posts plugin", function() {
    var server;
    server = new Hapi.Server();
    Lab.test('plugin successfully loads', function(done) {
      return server.pack.register({
        plugin: require('../plugins/posts')
      }, function(err) {
        Lab.expect(err).to.equal(void 0);
        return done();
      });
    });
    return Lab.test("Plugin registers routes", function(done) {
      var table;
      table = server.table();
      Lab.expect(table).to.have.length(1);
      Lab.expect(table[0].path).to.equal("/posts");
      return done();
    });
  });

}).call(this);
